### PR TITLE
removed react warnings

### PR DESCRIPTION
**Pull request by ronmnm**
removed react warnings

### CODE REVIEW

**Comment by mhluongo** [comment]
Thanks @ronmnm! @ironng leaving this to you to review and merge. You can get the CI to run after a manual review by pushing to our hosted repo, ala [`keep-core`](https://github.com/keep-network/keep-core/blob/master/scripts/run-forked-pr-build.sh)

**Comment by ronmnm** [comment]
Thanks for merging @ironng. I have a question about circleci, it runs automatically when I do PR? or I should do it by myself?

**Comment by ironng** [comment]
CI gets triggered after we manually push the PR to our repo after review. Circle isn't configured for any forks, so don't worry about it, but thank you for asking!

**Comment by mhluongo** [comment]
Rationale: we need to make sure env vars, etc aren't being tampered with @ronmnm - though it might not make as much sense for thisrepo, some of our CI jobs have deploy powers. You can always run locally though

**Pull request merged**
