### PR TITLE
Release: 0.17.0-rc (Ropsten)

### PR DESCRIPTION
**Pull request by sthompson22**
Picking up the latest wave of updates and fixes for tbtc-dapp + latest tbtc.js.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Pushed a new version of the RC.

**Comment by brandoncurtis** [comment]
bump tbtc.js:

```"@keep-network/tbtc.js": ">0.17.0-rc <0.17.0",```

https://www.npmjs.com/package/@keep-network/tbtc.js?activeTab=versions

**Comment by Shadowfiend** [comment]
https://github.com/keep-network/tbtc-dapp/pull/288/commits/77790a4afea76ce4c457e1bc0fcef343d98fcb40 :)

**Comment by sthompson22** [comment]
Coming through with 0.18.0 so closing this  one.

**Pull request closed without merging**
