### PR TITLE
Slick Moves: Set up tBTC config by chain id

### PR DESCRIPTION
**Pull request by Shadowfiend**
Rather than using isMainnet, provide a config indexed by chain id, and
use the already-looked-up chain id to determine which config to use at
load time. Config also now includes the local network.

Spinoff of keep-network/local-setup#40, though it doesn't block that PR.

In draft because I haven't had a chance to give it a full test yet, but if the
reviewer tests it satisfactorily I think we can land it. Whoever gets to it
first can review :wink:

### CODE REVIEW

**Comment by lukasz-zimnoch** [comment]
Looks good but the linter isn't happy:
```
/home/circleci/project/src/wrappers/web3.js
  3:16  error  'EthereumHelpers' is defined but never used  no-unused-vars
  3:33  error  'BitcoinHelpers' is defined but never used   no-unused-vars
```

**Comment by Shadowfiend** [comment]
🤔 must have missed setting up pre-commit locally. Will fix!

**Comment by Shadowfiend** [comment]
Oh yeah, I missed setting up pre-commit because I was working in the local-setup checkouts :grimacing: Might be useful to make `initialize-repositories` also set up pre-commit for completeness 🤔 Anyway, later haha.

**Comment by Shadowfiend** [comment]
This should be ready to go.

**Review by lukasz-zimnoch — APPROVED** [review]

**Comment by lukasz-zimnoch** [comment]
I approved but don't have write permissions to merge.

**Review by pdyraga — APPROVED** [review]

**Pull request merged**
